global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m
  receiver: 'selfheal-webhook'

receivers:
  - name: 'selfheal-webhook'
    webhook_configs:
      - url: 'http://<EC2_PUBLIC_IP>:5001/'
