- name: Restart NGINX if down
  hosts: localhost
  become: yes
  tasks:
    - name: Restart NGINX container with docker-compose
      command: docker-compose -f /home/ubuntu/self-heal/docker-compose.yml restart nginx
      args:
        chdir: /home/ubuntu/self-heal/
